[startup._ssh]
name = "bash"
must_exit = true
data = """
mkdir -p /var/run/sshd
"""

[startup.sshd]
after = ["_ssh"]
name = "execute"

[startup.sshd.args]
loglevels_db = '2'
domain = "core"
name = "/usr/sbin/sshd"
args = ["-D"]
