# Start the ipfs daemon, after the networkin is already configured
[startup.ipfs-daemon]
name = "system"
after = ["net"]
running_delay = 5

[startup.ipfs-daemon.args]
name = "ipfs"
args = ["daemon", "--init"]

# make sure /ipfs and /ipns are in place so we start the mount
[startup.ipfs-mount-init]
name = "bash"
running_delay = -1

[startup.ipfs-mount-init.args]
stdin = """
mkdir -p /ipfs
mkdir -p /ipns
"""

[startup.ipfs-mount]
name = "system"
after = ["ipfs-daemon", "ipfs-mount-init"]
running_delay = -1

[startup.ipfs-mount.args]
name = "ipfs"
args = ["mount"]